# Generated by Django 3.2.18 on 2023-03-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.CharField(max_length=50)),
                ('is_disponivel', models.BooleanField(default=True)),
                ('is_selecionado', models.BooleanField(default=False)),
            ],
        ),
    ]
