# Generated by Django 3.2.11 on 2023-03-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startgame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habil', models.BooleanField(default=True)),
                ('tempo_pelada', models.FloatField(default=10)),
                ('quantidade_jogadores', models.IntegerField(default=7)),
                ('valor_jogador', models.FloatField(default=10)),
                ('local', models.CharField(default='Society', max_length=50)),
                ('gols_time1', models.IntegerField(default=0)),
                ('gols_time2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habil', models.BooleanField(default=True)),
                ('nome_time', models.CharField(max_length=50)),
                ('cor_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='jogador',
            name='habil',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='time_pelada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habil', models.BooleanField(default=True)),
                ('pelada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startgame.pelada')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startgame.time')),
            ],
        ),
        migrations.AddField(
            model_name='time',
            name='Jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startgame.jogador'),
        ),
    ]
