# Generated by Django 3.2.11 on 2023-03-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startgame', '0002_auto_20230317_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelada',
            name='gols_time1',
        ),
        migrations.RemoveField(
            model_name='pelada',
            name='gols_time2',
        ),
        migrations.AddField(
            model_name='time_pelada',
            name='gols_time',
            field=models.IntegerField(default=0),
        ),
    ]
