# Generated by Django 3.2.11 on 2023-03-18 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startgame', '0004_auto_20230317_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='jogador',
        ),
        migrations.CreateModel(
            name='Time_jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habil', models.BooleanField(default=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startgame.jogador')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startgame.time')),
            ],
        ),
    ]
