# Generated by Django 3.2.18 on 2023-03-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startgame', '0009_auto_20230322_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.IntegerField(default=0),
        ),
    ]
