# Generated by Django 3.2.18 on 2023-03-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startgame', '0011_auto_20230324_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelada',
            name='corTime01',
            field=models.CharField(default='#ff0000', max_length=20),
        ),
        migrations.AddField(
            model_name='pelada',
            name='corTime02',
            field=models.CharField(default='#0000ff', max_length=20),
        ),
    ]
