# Generated by Django 3.2.18 on 2023-04-28 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notaseasy', '0003_auto_20230428_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
