# Generated by Django 3.2.18 on 2023-04-28 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notaseasy', '0004_alter_notafiscal_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscal',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notafiscal',
            name='object_id',
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='arquivo',
            field=models.FileField(default=1, upload_to='notas_fiscais/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Arquivo',
        ),
    ]
